# Generated by Django 3.2 on 2021-12-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
